name: Build Java Quarkus Application with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-application:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v7

    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file ./quarkus-demo-app/pom.xml

    # Required by the job "push-to-registry"
    - name: Upload compiled target artifacts
      uses: actions/upload-artifact@v7
      with:
        name: quarkus-target
        # The dockerfile will only require the directory "quarkus-app" in the TARGET
        # to build the container
        path: quarkus-demo-app/target/quarkus-app/
        retention-days: 1

    - name: List files in the output target directory
      run: |
        ls ${{ github.workspace }}/quarkus-demo-app/target


  build-image-and-push:

    runs-on: ubuntu-latest
    needs: build-application  # Ensures this job runs ONLY after build-application succeeds

    permissions:
      contents: read
      packages: write
      id-token: write # <-- Required for Sigstore keyless signing (using GitHub's OIDC identity [Keyless])

    steps:
    # We need again the source in order to get the Dockerfile
    - name: Checkout repository source
      uses: actions/checkout@v7

    # Get the generated TARGET directory from the previous JOB
    - name: Download target artifacts
      uses: actions/download-artifact@v8
      with:
        name: quarkus-target
        # Dockerfile looks for the path "target/quarkus-app/"
        path: quarkus-demo-app/target/quarkus-app/

    - name: Log in to Quay.io
      uses: docker/login-action@v4
      with:
# Create the following on GitHub: Project Repository > Settings > Secrets and variables > Actions
# Repository secrets name: QUAY_ROBOT_ACCOUNT and QUAY_ROBOT_TOKEN
# Repository variable name: QUAY_USERNAME
# Reference: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets#creating-secrets-for-a-repository
        registry: quay.io
        username: ${{ secrets.QUAY_ROBOT_ACCOUNT }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build and push Docker image
      # This ID is referenced by the "Attach SBOM to Quay Image" step.
      # This ID is referenced by the "ign and Attest SBOM to Image " step.
      id: build-image
      uses: docker/build-push-action@v7
      with:
        context: ./quarkus-demo-app
        file: ./quarkus-demo-app/src/main/docker/Dockerfile.jvm
        # This is the default architecture
        platforms: linux/amd64
        push: true
        tags: |
          quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app:${{ github.sha }}
          quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app:latest
        # Pulls existing cached layers directly from the repository's GitHub Actions cache storage
        #cache-from: type=gha
        #
        # Writes build layers back to GitHub Actions (gha) cache storage.
        # Setting mode=max instructs BuildKit to cache intermediate build stages (crucial for multi-stage Quarkus Dockerfiles),
        # rather than only the final output image layers.
        #cache-to: type=gha,mode=max



# ALTERNATIVE: how to build and pusth just by using "docker":
#
#    - name: Build and Push with standard Docker CLI
#      run: |
#        docker build \
#          -f ./quarkus-demo-app/src/main/docker/Dockerfile.jvm \
#          -t quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app:${{ github.sha }} \
#          ./quarkus-demo-app
#
#        docker push quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app:${{ github.sha }}



# Create a Software Bill of Materials (SBOM) manifest file to provide Red Hat Trusted Profile Analyzer (RHTPA)
# with the package data needed for security analysis.
# It is generated using the generated container image: it captures vulnerabilities in both code applicatoin
# and the operating system hosting it (the underlying base image).
#
# Generate SBOM using Anchore Syft
    - name: Generate SBOM (SPDX JSON)
      uses: anchore/sbom-action@v0
      with:
        image: quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app:${{ github.sha }}
# Red Hat Trusted Profile Analyzer supports SPDX and CycloneDX JSON formats
# CycloneDX is managed by OWASP while SPDX is managed by the Linux Foundation and is an ISO/IEC standard
# TPA only supports CycloneDX version 1.3, 1.4, 1.5, and 1.6, along with SPDX version 2.2, and 2.3.
        format: spdx-json@2.3
        output-file: sbom.spdx.json

    # Install Cosign CLI to attach the SBOM
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

#    - name: Attach SBOM to Quay Image
#      run: |
#        cosign attach sbom \
#          --type spdx \
#          --sbom sbom.spdx.json \
#          quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app@${{ steps.build-image.outputs.digest }}
      # Generate a signed attestation holding the SBOM
      # Cosign Attestations signs and attaches the SBOM simultaneously.
    - name: Sign and Attest SBOM to Image
      run: |
        # The --yes flag automatically answers YES: the command asks the user "Are you sure you would like to continue? [y/N]?"
        cosign attest \
          --yes \
          --type spdx \
          --predicate sbom.spdx.json \
          quay.io/${{ vars.QUAY_USERNAME }}/quarkus-demo-app@${{ steps.build-image.outputs.digest }}


